#!/bin/bash

# terminal output colors
yellow="\e[0;33m"
green="\e[0;32m"
bold="\e[1m"
color_reset="\e[0m"

# +++++++++++++++++++ CPU USAGE +++++++++++++++++++
# Reading first batch of idleCPUTime and totalCPUusageTime info from "/proc/stat" file
read -a cpu_time_stats < <(awk '$1 == "cpu" {
	total_cpu_time = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9;
	print $2, $3, $4, $5, $6, $7, $8, $9, total_cpu_time
}' /proc/stat)
cpu_idle_time1=${cpu_time_stats[3]}
total_cpu_usage_time1=${cpu_time_stats[8]}

sleep 1

# read second batch of idleCPUTime and totalCPUusageTime stats from "/proc/stat" file
read -a cpu_time_stats2 < <(awk '$1 == "cpu" {
	total_cpu_time = $2 + $3 + $4 + $5 + $6 + $7 + $8 + $9;
	print $2, $3, $4, $5, $6, $7, $8, $9, total_cpu_time
}' /proc/stat)
cpu_idle_time2=${cpu_time_stats2[3]}
total_cpu_usage_time2=${cpu_time_stats2[8]}

# find the differences in batch 1 and 2
(( diff_idle_cpu_time = cpu_idle_time2 - cpu_idle_time1  ))
(( diff_total_cpu_time = total_cpu_usage_time2 - total_cpu_usage_time1  ))

# calculating cpu usage percentage
cpu_usage_percent=$(
	awk -v idle="$diff_idle_cpu_time" -v total="$diff_total_cpu_time" 'BEGIN {printf "%.2f", (total - idle) / total * 100}'
)

echo -e "\n${yellow}${bold}Total CPU Usage: ${green}$cpu_usage_percent%${color_reset}"

# +++++++++++++++++++ MEMORY USAGE +++++++++++++++++++
awk '
	# function that converts fetched memory data from kbs to more readable sizes
	# unlike printf, sprintf returns a formatted string instead of printing it
	function convert_mem(mem) {
		if (mem >= 1048576){
			#  convert memory to GB
			return sprintf("%.2f GB", mem/1048576)
		} else if (mem >= 1024){
			#  convert memory to MB
			return sprintf("%.2f MB", mem/1024)
		} else {
			return sprintf("%d KB", mem)
		}
	}

	BEGIN { print "\n\033[1;33m--- Memory Usage ---\033[0m\n" }
	
	# grabbing total and available memory from file
	$1 == "MemTotal:" { total_mem=$2 }
	$1 == "MemAvailable:" { avilable_mem=$2 }
	END { 
		# calculating used memory
		memory_used = total_mem - avilable_mem
		# printing out the data fetched
		printf "Memory Used: \033[32m%s (%d%%)\033[0m\nAvailable Memory: \033[32m%s (%d%%)\033[0m\n",
		 convert_mem(memory_used), (memory_used/total_mem)*100, convert_mem(avilable_mem), (avilable_mem/total_mem)*100
	}
' /proc/meminfo

# +++++++++++++++++++ DISK USAGE +++++++++++++++++++
df -k | grep '^/dev/' | awk '
BEGIN { print "\n\033[1;33m--- Disk Usage ---\033[0m\n" }
{
	total_space += $2;
	used_space += $3;
	free_space += $4
}
END {
	# converting from KB to GB
	total_space_gb = total_space / 1048576
	used_space_gb = used_space / 1048576
	free_space_gb = free_space / 1048576

	# calculating percentage
	used_space_pct = (used_space / total_space) * 100
	free_space_pct = (free_space / total_space) * 100

	printf "Total space: \033[32m%.2fGB\033[0m\nUsed space: \033[32m%.2fGB (%.1f%%)\033[0m\nFree space: \033[32m%.2fGB (%.1f%%)\033[0m\n",
	 total_space_gb, used_space_gb, used_space_pct, free_space_gb, free_space_pct
}
'

# +++++++++++++++++++ Top 5 High CPU Usage Processes +++++++++++++++++++
echo -e "\n${yellow}${bold}--- Top 5 High CPU Usage Processes ---\n${green}"
ps -eo pcpu,comm,pid --sort=-pcpu | head -n 6 | column -t

# +++++++++++++++++++ Top 5 High Memory Usage Processes +++++++++++++++++++
echo -e "\n${yellow}${bold}--- Top 5 High Memory Usage Processes ---\n${green}"
ps -eo pmem,comm,pid --sort=-pmem | head -n 6 | column -t

echo -e "\e[0m"
